services:
  rag-service:
    image: rag-img
    container_name: rag-container
    command: ["/bin/bash", "-c", "nvidia-smi; nvcc --version; source /opt/conda/bin/activate rag_env; python --version; echo 'Hello World'; tail -f /dev/null"]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/code"
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]